[project]
name = "compiler2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "egglog>=11.3.0",
    "mypy>=1.18.2",
    "numpy>=2.3.3",
    "pytest>=8.4.2",
]
